### ISSUE TITLE
Ukrainian transliteration might be wrong

### ISSUE THREAD

**Issue by brainy** [danielshahaf/bilmiyorum#4]
The word "розмовляю" is transliterated as "rozmobl(y)ayu", but cyrillic **в** is latin **v**, not **b**. So the transliteration should probably be "rozmovlyayu". I don't know Ukrainian, so I can't say if it has the b/v voice change, in which case the transliteration would be correct. However, as a rule, Slavic languages don't.

**Comment by danielshahaf** [comment]
Good catch. I am no longer in contact with the Ukrainian speaker, and there's nothing in my original (non-public) notes about the pronunciation, so I think I'll change it: in the end, it's more likely to be a mistake than not. Thanks :-)

**Comment by danielshahaf** [comment]
Fixed. I'll deploy when I can. Thanks for the report!
